// Parses the plain-text resume (as generated by the AI prompt in App.jsx)
// into structured sections so the PDF templates can lay them out individually
// instead of dumping one big text block.

const KNOWN_HEADINGS = [
  "PROFESSIONAL SUMMARY",
  "SUMMARY",
  "PROFILE",
  "WORK EXPERIENCE",
  "EXPERIENCE",
  "EMPLOYMENT HISTORY",
  "EDUCATION",
  "SKILLS",
  "KEY SKILLS",
  "CORE SKILLS",
  "LANGUAGES",
  "CERTIFICATIONS",
  "WORK AUTHORIZATION",
  "VISA STATUS",
  "PERSONAL DETAILS",
  "ADDITIONAL INFORMATION",
];

function isHeadingLine(line) {
  const trimmed = line.trim();
  if (!trimmed) return false;
  const upper = trimmed.toUpperCase();
  if (trimmed === upper && trimmed.length < 40 && trimmed.length > 2) {
    return true;
  }
  return KNOWN_HEADINGS.some((h) => upper.startsWith(h));
}

export function parseResumeText(resumeText) {
  if (!resumeText) return { headerLines: [], sections: [] };

  const lines = resumeText.split("\n");
  const sections = [];
  let currentSection = null;
  let headerLines = [];
  let sawFirstHeading = false;

  for (let rawLine of lines) {
    const line = rawLine.trimEnd();

    if (isHeadingLine(line)) {
      sawFirstHeading = true;
      currentSection = { title: line.trim(), lines: [] };
      sections.push(currentSection);
      continue;
    }

    if (!sawFirstHeading) {
      if (line.trim()) headerLines.push(line.trim());
      continue;
    }

    if (currentSection) {
      currentSection.lines.push(line);
    }
  }

  if (sections.length === 0 && headerLines.length > 0) {
    return {
      headerLines: [],
      sections: [{ title: "RESUME", lines: headerLines }],
    };
  }

  return { headerLines, sections };
}

export function splitSectionIntoBlocks(sectionLines) {
  const blocks = [];
  let currentBlock = null;

  for (let line of sectionLines) {
    const trimmed = line.trim();
    if (!trimmed) {
      currentBlock = null;
      continue;
    }
    const isBullet = /^[-•*]\s+/.test(trimmed);

    if (isBullet) {
      if (!currentBlock || currentBlock.type !== "bullets") {
        currentBlock = { type: "bullets", items: [] };
        blocks.push(currentBlock);
      }
      currentBlock.items.push(trimmed.replace(/^[-•*]\s+/, ""));
    } else {
      blocks.push({ type: "line", text: trimmed });
      currentBlock = null;
    }
  }

  return blocks;
}
